[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rspotify = { version = "0.15.0", features = ["cli", "env-file"] }
serde_json = "1.0.141"
tokio = { version = "1", features = ["full"] }
